#!/usr/bin/env python
#     Copyright 2016, Kay Hayen, mailto:kay.hayen@gmail.com
#
#     Part of "Nuitka", an optimizing Python compiler that is compatible and
#     integrates with CPython, but also works on its own.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
import sys, os, subprocess
if __name__ == "__main__":
    for ver in ("3.3", "3.2"):
        path = "/usr/bin/python" + ver
        nuitka_cmd = "nuitka-run" if os.path.basename(sys.argv[0]).lower().startswith("nuitka-run") else "nuitka"
        if os.path.exists(path):
            cmd = [nuitka_cmd, "--python-version=%s" % ver]
            cmd += sys.argv[1:]
            subprocess.Popen(
                cmd,
                stdout = sys.stdout,
                stderr = sys.stderr,
                stdin  = sys.stdin,
                shell  = 0
            ).wait()
            os._exit(0)
    sys.stderr.write("error: python 3 not available\n")
    sys.stderr.flush()
    os._exit(1)
